### ISSUE TITLE
Possibly consider simplified ALCC method to run under the hood of `boot_mod_alcc()`

### ISSUE THREAD

**Issue by austinwpearce** [adriancorrendo/soiltestcorr#15]
_The following is a non-urgent idea to consider (and may be a non-issue for some users). With that said..._

In a future version of soiltestcorr, might we consider a simplified version of mod_alcc() that only does the minimum steps needed to calculate the CSTV. Maybe it could be called alcc_cstv() or something. This simpler version would skip calculating extra things like the predicted curve and AIC and such.

The purpose behind this could be to use this simpler version of mod_alcc() inside boot_mod_alcc(). I would imagine that doing so would probably result in boot_mod_alcc() running faster on thousands of resamples because in each iteration, it would be calculating fewer things.

**Comment by adriancorrendo** [comment]
Austin, I'll keep an eye on this. However, I haven't experienced any issues when running the boot_alcc().
I think some users may find value on having the resampling for the curve, AIC, etc. For example, I have used myself RMSE, AIC derived as a median from the bootstrapping. I prefer these estimates over single estimatations. The same with the curve, users may like to plot how the curve varies across resamples or get a summarized curve. 

Best,
Adrian

**Comment by austinwpearce** [comment]
Thanks for the consideration. The "time saved" probably doesn't warrant the lost information. Thanks
